### ISSUE TITLE
Implement user (gamer) registration form

### ISSUE THREAD

**Issue by etsets** [etsets/wheel-of-fortune-stoiximan-2#2]
- Implement using VS template (extend initial model, view and controller) User registration.

Consider password limitations and e-mail address correctness as decided during the design (specifications).

**Comment by pbariamoglou** [comment]
**Done**

1. _FaceApi check_  -> in AccountController , Register Action (/account/register) instead of using another Controller (/api/images/upload)

2. _Upload with random name to Azure_   -> in AccountController , Register Action (/account/register) instead of using another Controller (/api/images/upload)

**Remains**

1.  _validation for Birthday > 21_ ,  also convert datetime to date

2. _check image extension_ , allow only image extensions

3.  _change the message that return if something fails_ , for each case of failure (ex eMail exists, the Image does not contain Face etc). Current behavior returns to /Register

**Comment by pbariamoglou** [comment]
1. Added the validation for Age > 21. Also changed the Display Format of Birthday in RegisterView(), the change of column attribute in Db.Table is not necessary 

2. Added the Validation for the Photo Image file so it accepts only .jpg, .jpeg,.png formats and maximum size 2mb.
